# NOTE: if you are editing this, try using the lint tool to check your work before pushing: https://forge.outer.jhuapl.edu/ci/lint

before_script:
  - echo "running CI jobs for HIRS"

stages:
  - build

gradle_build:
  stage: build
  script: ./gradlew build
  artifacts:
    when: on_failure
    untracked: true
    expire_in: 3 days

rpm_build_centos6:
  stage: build
  script: ONLY_BUILD_EL6_RPMS=true ./package/package.centos.sh
  artifacts:
    paths:
      - package/rpm/RPMS/
    expire_in: 3 days

rpm_build_centos7:
  stage: build
  script: ONLY_BUILD_EL7_RPMS=true ./package/package.centos.sh
  artifacts:
    paths:
      - package/rpm/RPMS/
    expire_in: 3 days
